### ISSUE TITLE
Cannot find module 'mongodb'

### ISSUE THREAD

**Issue by tgoldenberg** [gadicc/meteor-react-hotloader#1]
@gadicc, Really excited for this. 

Currently using `Meteor 1.3-modules-beta.7`, as suggested, and I follow the instructions, yet I get this error when I run `meteor`. 

<img width="518" alt="screen shot 2016-02-10 at 11 30 04 am" src="https://cloud.githubusercontent.com/assets/10930134/12953809/0022b8ba-cfea-11e5-9c86-17a6e2745edb.png">

Any suggestions? Thanks!

**Comment by gadicc** [comment]
Our first issue :)

It's a really strange error, but now that we're in atmosphere, you can delete all the hot-related stuff from your app's `packages` dir and just run it like a regular package.  I think it will fix this too.  Let me know.

**Comment by gadicc** [comment]
Or have you already done that?  I might be a bit rusty with Meteor error messages, but the 3rd line from the bottom made suspect it's in your app.

I'm assuming you've never experienced this with other packages that require things from npm?

**Comment by tgoldenberg** [comment]
No, I am only referencing the `ecmascript-hot` package as described in the README. Here are my Meteor packages and `package.json` file in case that helps. https://gist.github.com/tgoldenberg/57c68e47380e9c4c8f8b

**Comment by gadicc** [comment]
This is a super strange one... I'm requiring `mongodb` exactly according to the package spec, and in the same way that the package is getting `meteor-babel`, etc.  And assuming of course that the regular `ecmascript` is working.  I also can't reproduce on my end.

The only thing I can really think of is I noticed that your package.json (thanks for sending!) also includes `mongodb` and maybe the version constraint is blocking it from using a lower version.  Can you try change it from 2.1.7 to 2.1.4 and see if this makes any difference?  If this is the issue and you need 2.1.7, I'll bump our deps on the next release.

What OS are you on?

**Comment by tgoldenberg** [comment]
Hi @gadicc, unfortunately same error with that change. I might try taking a stab with a fresh project, but it's too bad because our current project could really use it.

**Comment by tgoldenberg** [comment]
So I got it running fine on a new project, but can't figure out how to integrate it with the old. At least it works though :)

**Comment by tgoldenberg** [comment]
Also, maybe a separate issue, but I find that it doesn't reload when I add HTML to my react component. For example, if I add another <p> tag within my `render` function, it doesn't appear at all.

**Comment by gadicc** [comment]
Haha, ok, thanks.  Is there any chance you can share a repo if your current code base, so I can try figure this out?

**Comment by tgoldenberg** [comment]
Hi @gadicc, it's for a company so I unfortunately cannot. I'm going to try to take apart the pieces and see if I can debug it a bit today, so I'll report back my findings

**Comment by tgoldenberg** [comment]
@gadicc Finally got this going, but hard to pinpoint what went wrong. Maybe because I tried to do the configuration pre-atmosphere? Could also be that the particular branch I was on didn't have the right Meteor version. Anyhow, very grateful for this!

**Comment by gadicc** [comment]
Thanks for reporting back!  Glad you're up and running, hopefully the issue won't recur.  It's possible from using the pre-atmosphere versions, but I think unlikely... it's a case that Meteor should have figured out, not really sure where things were going wrong.  Let me know if this happens again, and happy you're enjoying :)
