### ISSUE TITLE
'react-redbox' is not in the npm registry

### ISSUE THREAD

**Issue by xcv58** [gadicc/meteor-react-hotloader#11]
I double checked on several servers:
```
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/react-redbox
npm ERR! 404
npm ERR! 404  'react-redbox' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

**Comment by sarasate** [comment]
I guess its redbox-react..

**Comment by gadicc** [comment]
Oops, that's my bad.  It's redbox-react ☺️  will fix the README when i get home. 

On 18 March 2016 4:50:24 PM SAST, Yihong <notifications@github.com> wrote:
>I double checked on several servers:
>```
>npm ERR! node v5.7.0
>npm ERR! npm  v3.6.0
>npm ERR! code E404
>
>npm ERR! 404 Registry returned 404 for GET on
>https://registry.npmjs.org/react-redbox
>npm ERR! 404
>npm ERR! 404  'react-redbox' is not in the npm registry.
>npm ERR! 404 You should bug the author to publish it (or use the name
>yourself!)
>npm ERR! 404
>npm ERR! 404 Note that you can also install from a
>npm ERR! 404 tarball, folder, http url, or git url.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     /tmp/npm-debug.log
>```
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gadicc/meteor-react-hotloader/issues/11

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xcv58** [comment]
I already sent you two PR (sorry for the first one, I have typo in the commit message as well :)

One more thing: I get error below if I use `gadicc:ecmascript-hot@0.0.11-rc.2` in `.meteor/package`:
```
   While selecting package versions:
   error: No version of gadicc:ecmascript-hot satisfies all constraints: @0.0.11-rc.2
   Constraints on package "gadicc:ecmascript-hot":
   * gadicc:ecmascript-hot@0.0.11-rc.2 <- top level
```

I have to use `gadicc:ecmascript-hot` instead of `gadicc:ecmascript-hot@0.0.11-rc.2` to fix this.

Could you confirm that you want to pin the version?

**Comment by gadicc** [comment]
Dang, no, it should be 0.0.9-rc.2 😕  i was rushing out when I did the README, was a mistake to rush the docs.  Will fix when I'm home unless you offering another PR?  ☺️

**Comment by xcv58** [comment]
Sure, please merge the PR.

**Comment by gadicc** [comment]
Thanks so much @xcv58 for all the help today.
