### ISSUE TITLE
How to make this package work with Flow Router SSR?

### ISSUE THREAD

**Issue by sammkj** [gadicc/meteor-react-hotloader#17]
I keep getting this error when I do `meteor`  with FlowRouter SSR:

```
					throw(ex);
W20160329-11:21:04.996(-5)? (STDERR) 						      ^
W20160329-11:21:05.030(-5)? (STDERR) Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
```

I had to do `meteor --production`  or explicitly set `BABEL_ENV=production meteor` to make the error go away. The problem is if I do this, I don't get instant react update. Any pointers to fix this would be greatly appreciated!

**Comment by gadicc** [comment]
I admit this was something I didn't originally consider (needing different babel config for the server/client), but it was recently pointed out to me by jedwards [here](https://forums.meteor.com/t/help-test-babelrc-support-in-native-meteor/19695/2?u=gadicc).  You can see the discussion in there, or, **in short, this will be addressed in the next release or two**.

**Comment by gadicc** [comment]
@sammkj can you try `gadicc:ecmascript-hot@1.3.0-2` after reading the upgrade notes in the [History.md](http://github.com/gadicc/meteor-react-hotloader/tree/master/History.md) and new sample `.babelrc` files at the end of the [README](http://github.com/gadicc/meteor-react-hotloader/tree/master/README.md) and see if this solves this for you?

**Comment by sammkj** [comment]
thank you @gadicc for fixing this! However I don't think this is working with FlowRouter SSR. FR requires  a shared folder to make SSR work. It seems like the new update is looking for `client` folder only.

**Comment by gadicc** [comment]
Ah, damn :(  No, we look for any client compilation now, however, the server restart (from a change in server/both code) kills react-hotloader before it can get the update across.  I'll have to think about this some more.  Thanks for the update.

**Comment by gadicc** [comment]
I think this should be working now, can you check when you have a chance?

Since `gadicc:ecmascript-hot@1.3.0_5` (just remove the @version and meteor update now).

**Comment by sammkj** [comment]
:scream: I just tested the newest version. It's working perfectly! However it's not nearly as fast as reloading components in `client` folder.

**Comment by gadicc** [comment]
Great stuff!  (for the first part)

Thanks for reporting back.

I'm going to close this issue and track the speed part in #26.
