### ISSUE TITLE
very weird "Unable to resolve some modules:" error

### ISSUE THREAD

**Issue by ChrisOHu** [gadicc/meteor-react-hotloader#25]
Hi @gadicc ,
Sorry had to open another issue, but I had this very strange issue, you can see below, not sure this is related to meteor-react-hotloader, but I do have these npm modules installed. Do you have any clues ?

Thanks : )

```
Unable to resolve some modules:

  "/Users/chrishu/Projects/IncV2/upweb/node_modules/redbox-react/lib/index.js" in
/Users/chrishu/Projects/IncV2/upweb/imports/containers/NotFoundPage.js (os.osx.x86_64)
  "/Users/chrishu/Projects/IncV2/upweb/node_modules/react-transform-catch-errors/lib/index.js" in
/Users/chrishu/Projects/IncV2/upweb/imports/containers/NotFoundPage.js (os.osx.x86_64)
  "/Users/chrishu/Projects/IncV2/upweb/node_modules/react-transform-hmr/lib/index.js" in
/Users/chrishu/Projects/IncV2/upweb/imports/containers/NotFoundPage.js (os.osx.x86_64)
```

**Comment by gadicc** [comment]
That is strange.  Is there any chance the installation failed?  Maybe try `npm install --save-dev redbox-react` on it's own and see if there are any specific errors and if not try again.  Can you confirm that `node_modules/redbox-react` exists and that it contains a `lib/index.js` ?

**Comment by gadicc** [comment]
Wait, none of those are found.  Is it possible that maybe you didn't run the original `npm install` line from the README in your project root, perhaps?

**Comment by ChrisOHu** [comment]
Actually I do have ```redbox-react react-transform-catch-errors react-transform-hmr ``` installed in the node_modules/, also the ```lib/index.js``` exists.

**Comment by ChrisOHu** [comment]
Hi @gadicc , also this only happened after I added ```flow-router``` and ```react-mount```, could this be related ?

Here's the ```lib/routes.js'''
```
import { Meteor } from 'meteor/meteor';
import App from '../imports/containers/App'
import HomePage from '../imports/containers/HomePage'
import LoginPage from '../imports/containers/LoginPage'
import NotFoundPage from '../imports/containers/NotFoundPage'
import { FlowRouter } from 'meteor/kadira:flow-router';
import { mount, withOptions } from 'react-mounter';

const MOUNT = withOptions({
  rootId: 'root',
  rootProps: {
    className: '',
    style: {
      height: '100%'
    }
  }
}, mount);

FlowRouter.route("/", {
  action: function() {
    if (Meteor.userId()) {
      FlowRouter.go("/home");
    } else {
      FlowRouter.go("/login");
    }
  }
});

FlowRouter.route("/login", {
  action: function() {
    if (Meteor.userId()) {
      FlowRouter.go('home');
    }
    MOUNT(App, {
      content: () => (<LoginPage {...arguments} />)
    });
  }
});

FlowRouter.route("/home", {
  action: function() {
    if (!Meteor.userId()) {
      FlowRouter.go('/login');
    }
    MOUNT(App, {
      content: () => (<HomePage {...arguments} />)
    });
  }
});

FlowRouter.notFound = {
  action: function() {
    MOUNT(App, {
      content: () => (<NotFoundPage {...arguments} />)
    });
  }
};

```

**Comment by ChrisOHu** [comment]
Ok...confirmed~
I reverted my codes to a point which meteor-react-hotloader worked, then I added flow-router/react-mount and added lib/routes.js, then the above errors would occur, as pasted below:

```
Unable to resolve some modules:

  "/Users/chrishu/Projects/IncV2/upweb/node_modules/redbox-react/lib/index.js" in
/Users/chrishu/Projects/IncV2/upweb/imports/containers/NotFoundPage.js (os.osx.x86_64)
  "/Users/chrishu/Projects/IncV2/upweb/node_modules/react-transform-catch-errors/lib/index.js" in
/Users/chrishu/Projects/IncV2/upweb/imports/containers/NotFoundPage.js (os.osx.x86_64)
  "/Users/chrishu/Projects/IncV2/upweb/node_modules/react-transform-hmr/lib/index.js" in
/Users/chrishu/Projects/IncV2/upweb/imports/containers/NotFoundPage.js (os.osx.x86_64)

W20160405-13:22:55.520(8)? (STDERR)
W20160405-13:22:55.521(8)? (STDERR) /Users/chrishu/.meteor/packages/meteor-tool/.1.3.0_3.1us8lpe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160405-13:22:55.522(8)? (STDERR)             				throw(ex);
W20160405-13:22:55.522(8)? (STDERR)             				      ^
W20160405-13:22:55.675(8)? (STDERR) Error: Cannot find module '/Users/chrishu/Projects/IncV2/upweb/node_modules/redbox-react/lib/index.js'
W20160405-13:22:55.675(8)? (STDERR)     at require (packages/modules-runtime.js:95:19)
W20160405-13:22:55.675(8)? (STDERR)     at meteorInstall.imports.containers.App.js (/Users/chrishu/Projects/IncV2/upweb/.meteor/local/build/programs/server/app/app.js:214:14)
W20160405-13:22:55.675(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160405-13:22:55.676(8)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160405-13:22:55.676(8)? (STDERR)     at meteorInstall.lib.routes.js (lib/routes.js:2:1)
W20160405-13:22:55.676(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160405-13:22:55.676(8)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160405-13:22:55.676(8)? (STDERR)     at /Users/chrishu/Projects/IncV2/upweb/.meteor/local/build/programs/server/app/app.js:1002:1
W20160405-13:22:55.676(8)? (STDERR)     at /Users/chrishu/Projects/IncV2/upweb/.meteor/local/build/programs/server/boot.js:283:10
```

**Comment by ChrisOHu** [comment]
Ok now things worked, after putting routes.js into imports/, and importing it from client/main.js : )  
Though strangely ~~

**Comment by gadicc** [comment]
I'm really glad you have this working, because, in my limited understanding of life, the universe and everything, this makes absolutely no sense :>  Can't argue with fact though.

If you repo is public, can you paste those 3 commits hash's here for reference?  (working, adding packages / not working, moving imports / working again).  I don't think I'll have a chance to look at this any time soon but would love to have that all written down.

And in case you ever figure out what was going here, let me know!  Otherwise yeah glad you're live again.

**Comment by ChrisOHu** [comment]
Haha : ) Anyway just glad it's working now :smiley:

**Comment by ChrisOHu** [comment]
After some experiments, I decided to not use routing since in a single page app I could simply control which view to show, like the native counterpart...
Also things seems really simple then : )

**Comment by gadicc** [comment]
I must admit, I'm my current project, I'm just using FlowRouter to update the route in redux, but otherwise only mount once and yeah, control what's shown via react.  Did you checkout the jsx-control-statements babel plugin?

**Comment by ChrisOHu** [comment]
Hi @gadicc , sorry for the late reply, didn't install  jsx-control-statements , might be the cause. But anyway I have switched to react-router : ) wishes~
