### ISSUE TITLE
Possible issue with Meteor Guide testing method

### ISSUE THREAD

**Issue by tomRedox** [gadicc/meteor-react-hotloader#27]
Hey, I've just tried to run my tests, I think for the first time since I installed a version of hotloader that has the babel stuff.  I'm now getting this error:

```
I20160405-18:31:41.661(1)? Creating C:\Users\Tom\AppData\Local\Temp\meteor-test-run141zaoe\client\.babelrc
W20160405-18:31:41.666(1)? (STDERR) 
W20160405-18:31:41.666(1)? (STDERR) C:\Users\Tom\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:
245
W20160405-18:31:41.666(1)? (STDERR)                                             throw(ex);
W20160405-18:31:41.666(1)? (STDERR)                                                   ^
W20160405-18:31:41.666(1)? (STDERR) Error: ENOENT, no such file or directory 'C:\Users\Tom\AppData\Local\Temp\meteor-test-run141zaoe\client\.babelrc'
W20160405-18:31:41.666(1)? (STDERR)     at Object.fs.openSync (fs.js:439:18)
W20160405-18:31:41.667(1)? (STDERR)     at Object.fs.writeFileSync (fs.js:978:15)
W20160405-18:31:41.667(1)? (STDERR)     at hot.lastHash (packages\gadicc_babel-compiler-hot.js:88:8)
W20160405-18:31:41.667(1)? (STDERR)     at packages\gadicc_babel-compiler-hot.js:190:4
W20160405-18:31:41.667(1)? (STDERR)     at packages\gadicc_babel-compiler-hot.js:625:3
W20160405-18:31:41.668(1)? (STDERR)     at C:\Users\Tom\AppData\Local\Temp\meteor-test-run141zaoe\.meteor\local\build\programs\server\boot.js:283:10
W20160405-18:31:41.668(1)? (STDERR)     at Array.forEach (native)
W20160405-18:31:41.668(1)? (STDERR)     at Function._.each._.forEach (C:\Users\Tom\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\server-
lib\node_modules\underscore\underscore.js:79:11)
W20160405-18:31:41.668(1)? (STDERR)     at C:\Users\Tom\AppData\Local\Temp\meteor-test-run141zaoe\.meteor\local\build\programs\server\boot.js:133:5
=> Exited with code: 8
```

I'm using the testing approach detailed here http://guide.meteor.com/testing.html#running-unit-tests and running the testing with `meteor test --driver-package practicalmeteor:mocha --port 3100`

If I switch back to `ecmascript` instead of `gadicc:ecmascript-hot` in the packages file the testing works fine.  It seems like the hot code doesn't like running in the test environment and maybe can't see the .babelrc file?  I don't know enough about how the testing works to know if that's an issue with the test harness or with this module?

**Comment by gadicc** [comment]
Hey Tom, just confirming that this is on my radar, was working on the 'faster' code first, which is hopefully done now pending testing.  More details in https://github.com/gadicc/meteor-react-hotloader/issues/26#issuecomment-207743140.

The problem is that Meteor isn't copying the .babelrc files into the test environment.  I'll have to see if inside the test environment I can figure out the original project directory.  Otherwise I believe official Meteor `.babelrc` is planned for the next `1.3.2` release... in which case it's easier for them to fix by simply copying those files over on a test run.

**Comment by gadicc** [comment]
@tomRedox I'm going to continue tracking this in #37.
