### ISSUE TITLE
hot react reload is not working

### ISSUE THREAD

**Issue by sammkj** [gadicc/meteor-react-hotloader#29]
I keep getting this error whenever I'm editing something outside of the `render()`:

```
hot-client.js:86 Uncaught TypeError: Cannot read property 'c' of undefined
```

**Comment by sammkj** [comment]
couldn't reproduce. Probably it's something that I messed up

**Comment by gadicc** [comment]
If you come across this again, paste the full file here.  From what I recall, this can happen when adding a new import, but only once.  But yes, will happily accept samples that cause this if you come across again.
