### ISSUE TITLE
[1.3.2-fast.12] My changes from PR https://github.com/gadicc/meteor-react-hotloader/pull/40 are not there

### ISSUE THREAD

**Issue by clayne11** [gadicc/meteor-react-hotloader#42]
`babel-compiler-hot/hothacks.js` does not have the RegEx changes from [my PR](https://github.com/gadicc/meteor-react-hotloader/pull/40).

**Comment by clayne11** [comment]
Looks like you accidentally undid them in https://github.com/gadicc/meteor-react-hotloader/commit/c367dfcfde54ffcdc874fc8dabab455ae069f585

**Comment by clayne11** [comment]
PR https://github.com/gadicc/meteor-react-hotloader/pull/43

**Comment by gadicc** [comment]
Wow, this is pretty scary.  The only thing I can think of is that my editor usually watches for changes on open files (e.g. on `git pull`), and I updated to a nightly release recently to fix something else.  I'll have to look into this quite seriously.  Thanks for pointing this out.
