### ISSUE TITLE
export default doesn't work?

### ISSUE THREAD

**Issue by gsabran** [gadicc/meteor-react-hotloader#44]
`export default onFail = (err) => { ... }`

raises error `ReferenceError: onFail is not defined`

**Comment by clayne11** [comment]
This has nothing to do with `meteor-react-hotloader` - your module syntax is wrong.

It's either a default export:

`export default (err) => { ... }`

or a named export

`export const onFail = (err) => { ... }`

Yours is a mix of both.

**Comment by gsabran** [comment]
I see, it makes sense. Weird that the named default export is still working in normal Meteor
