### ISSUE TITLE
Cannot load local meteor package

### ISSUE THREAD

**Issue by gsabran** [gadicc/meteor-react-hotloader#47]
`import {clientErrorLog} from 'meteor/gsabran:utils';` (where `gsabran:utils` is a local meteor package that I've under my `./packages` folder, and that is listed in `./meteor/packages`) throw an error on the client: `Uncaught Error: Cannot find module 'meteor/gsabran:utils'` and the app crashes. It works fine without `meteor-react-hotloader`

**Comment by gadicc** [comment]
I can't reproduce this.  What versions of Meteor and ecmascript-hot are you using?

I tested with Meteor 1.3.2.1 and `gadicc:ecmascript-hot@1.3.2-fast.12` (which is an experimental release, but contains all the latest code).

**Comment by gsabran** [comment]
I've upgraded. I still have a similar issue:

`Error: Can't find npm module 'meteor/react-meteor-data'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?`

Here's the trace: 

      /Users/me/.meteor/packages/meteor-tool/.1.3.2_2.rc1dz9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
                        throw(ex);
                              ^
     Error: Can't find npm module 'meteor/react-meteor-data'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
         at Object.Npm.require (/PathToRepo/.meteor/local/build/programs/server/boot.js:195:17)
         at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
         at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
         at meteorInstall.server.emails.notificationsEmail.jsx (server/emails/notificationsEmail.jsx:4:1)
         at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
         at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
         at /PathToRepo/.meteor/local/build/programs/server/app/app.js:4501:1
         at /PathToRepo/.meteor/local/build/programs/server/boot.js:283:10
         at Array.forEach (native)
         at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.3.2_2.rc1dz9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/    node_modules/underscore/underscore.js:79:11)

`server/emails/notificationsEmail.jsx` starts with 

    import juice from 'juice';
    import {ReactMeteorData} from 'meteor/react-meteor-data';

Let me know if more detail on the stack trace would help, since line numbers are pretty meaningless

**Comment by gadicc** [comment]
Thanks!  Any chance you can put the entire project on github for me to take a look at?

Perhaps you can also start a fresh project and see if the same error occurs, so we can see if there's something specific to your project or machine?  Seems to be working for others on OSX so don't think that's the issue.

**Comment by gsabran** [comment]
Well turns out `react-meteor-data` was missing from my `.meteor/packages`... I don't know how it got kicked out and was not failing before. Conclusion is that upgrading to the latest meteor and ecmascript-hot fix the issue. Thanks for the attention!

**Comment by gadicc** [comment]
Great stuff!  Thanks for reporting back.  These kind of strange things happen to me from time to time and I've learnt not to question them ;)
