### ISSUE TITLE
String escape sequences throwing errors

### ISSUE THREAD

**Issue by tgoldenberg** [gadicc/meteor-react-hotloader#5]
So our website uses a lot of textual data from news sources, and so it's unavoidable that there be some apostrophes in the text. What I find is that this breaks the hot loading. With static text, I can set it to a variable to be read - `let titleMsg = "What's your name?"` `<p>{titleMsg}</p>`

Is there a way to fix this within the package, or should this just be noted in the README? 

<img width="1098" alt="screen shot 2016-02-12 at 4 25 21 pm" src="https://cloud.githubusercontent.com/assets/10930134/13020786/4e959f64-d1a5-11e5-8256-daaa1e1dc9a1.png">

**Comment by tgoldenberg** [comment]
<img width="426" alt="screen shot 2016-02-12 at 4 28 47 pm" src="https://cloud.githubusercontent.com/assets/10930134/13020865/bc49dfac-d1a5-11e5-89a5-eb19994578d4.png">

**Comment by gadicc** [comment]
I didn't completely understand, but this definitely sounds like a bug that we need to fix.  Can you paste some of the source code that is triggering this error, together with the corresponding generated code in hot.js (at the given line number)?  Assuming this doesn't happen with the regular `ecmascript` package in the same Meteor beta version.

**Comment by tgoldenberg** [comment]
Hi @gadicc, so I'll share some shots of what the file looks like and the error I'm getting. Basically, the `'` character is throwing errors in the hot loading system.
<img width="1107" alt="screen shot 2016-02-16 at 10 57 39 am" src="https://cloud.githubusercontent.com/assets/10930134/13081825/35fd89fe-d49c-11e5-92f6-5a2abfa78d89.png">
<img width="865" alt="screen shot 2016-02-16 at 10 57 32 am" src="https://cloud.githubusercontent.com/assets/10930134/13081826/35ff48d4-d49c-11e5-9e37-9de06242ee2f.png">
![screen shot 2016-02-16 at 10 57 27 am](https://cloud.githubusercontent.com/assets/10930134/13081827/3601203c-d49c-11e5-9522-d0347a3b694b.png)

**Comment by gadicc** [comment]
Hey sorry, I'm overseas atm but will get to this as soon as I have a chance.  Thanks for the screenshots.

**Comment by gadicc** [comment]
hey @tgoldenberg, I can't seem to reproduce this.  Tried both:

```html
        <AlertCard text={"Choose which feed's results"} />
        <AlertCard text={"Choose which feed\'s results"} />
```

with

```js
const AlertCard = ({text}) => ( <div>Alert: {text}</div> );
```

and all work fine.  Can you share your component code or even better, a small reproduction on github?

**Comment by tgoldenberg** [comment]
So the problem is if the text is hard-coded in, not if it's passed as `props`. I'll see if I can post a sample soon.

**Comment by gadicc** [comment]
Tried also:

```js
class AlertCard extends Component {
  render() {
    // let text = "What";
    // let text = "What's up?";
    let text = "What\'s up?";
    return (
      <div>Alert: {text}</div>
    );
  }
}
```

:)

Thanks, sample would be great!

**Comment by gadicc** [comment]
@tgoldenberg, it sounds like you stopped having this error, but I finally found a way to reproduce it :)  The fix will be included in the next release.
