### ISSUE TITLE
Improve recognition of stateless components

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-react-hotloader#6]
See the README for how we currently handle it.

I have a few more ideas to cover more cases without breaking anything else, when I have a chance.

**Comment by gadicc** [comment]
@mordra, `v0.0.7-beta.12` accepts the other kind of functional components now (full function code, not just a map to jsx), i.e.

```js
const MyComponent = ({prop1, prop2}) => {
  // must include /return\s+\(/, i.e. "return", whitespace, "("
  return ( ... )
};
```

Yeah, this is a lot less painful than hand coverting the components :)

**Comment by mordra** [comment]
@gadicc hey, you new changes looks awesome!! and I've been keeping an eye on the meteor topic. 

Just been really busy with tech interviews over the last week, haven't had a chance to get back to my project.

I'll be getting back into it soon and let you know how it all goes.

**Comment by gadicc** [comment]
Thanks, man.  Yeah, it was a bit rough trying to maintain this during an overseas trip, but now that I'm back I got to do some major improvements and I'm enjoying it so much more my self now too.

Good luck with the interviews!
