### ISSUE TITLE
Error: locals does not appear to be 'module' object ...

### ISSUE THREAD

**Issue by spherop** [gadicc/meteor-react-hotloader#7]
After attempting installation. Seems to be some config issue. 

Fails to launch with:

`W20160218-15:34:03.513(-8)? (STDERR)
W20160218-15:34:03.514(-8)? (STDERR) /Users/dpnewman/.meteor/packages/meteor-tool/.1.1.13-modules.7.ip1bjg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160218-15:34:03.515(-8)? (STDERR)            				throw(ex);
W20160218-15:34:03.515(-8)? (STDERR)            				      ^
W20160218-15:34:03.602(-8)? (STDERR) Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
W20160218-15:34:03.602(-8)? (STDERR)     at proxyReactComponents (/Users/dpnewman/Meteor/haven-app/.meteor/local/build/programs/server/packages/modules.js:21750:11)
W20160218-15:34:03.602(-8)? (STDERR)     at meteorInstall.both.lib.authorizeForRole.jsx (/Users/dpnewman/Meteor/haven-app/.meteor/local/build/programs/server/app/app.js:59:59)
W20160218-15:34:03.603(-8)? (STDERR)     at fileEvaluate (/Users/dpnewman/Meteor/haven-app/.meteor/local/build/programs/server/packages/modules-runtime.js:219:9)
W20160218-15:34:03.603(-8)? (STDERR)     at require (/Users/dpnewman/Meteor/haven-app/.meteor/local/build/programs/server/packages/modules-runtime.js:92:20)
W20160218-15:34:03.603(-8)? (STDERR)     at /Users/dpnewman/Meteor/haven-app/.meteor/local/build/programs/server/app/app.js:12405:1
W20160218-15:34:03.603(-8)? (STDERR)     at /Users/dpnewman/Meteor/haven-app/.meteor/local/build/programs/server/boot.js:242:10
W20160218-15:34:03.603(-8)? (STDERR)     at Array.forEach (native)
W20160218-15:34:03.603(-8)? (STDERR)     at Function._.each._.forEach (/Users/dpnewman/.meteor/packages/meteor-tool/.1.1.13-modules.7.ip1bjg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160218-15:34:03.603(-8)? (STDERR)     at /Users/dpnewman/Meteor/haven-app/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8`

**Comment by gadicc** [comment]
@spherop:

> @gadicc I do indeed have beta 7. i am gonna try a more vanilla project and add some things in assuming something is conflicting. will report back. 
EDIT: do not have my own .babelrc

Did you have any luck on another project?

You wrote "fails to launch".  Are you saying this happens on first load, before modifying any files?

Does this affect all files or just some files?  Can you confirm these files are in your app and not in a package (hot loading isn't supported in packages with our current strategy)?  If just some files, can you give an example of such a file, including it's location?

Are you able to share your project or a small reproduction?

Thanks!

p.s. the `beta.11` seems to be working great :)

**Comment by gadicc** [comment]
Hey, there have been quite a few changes since then...  if you're still using the project and still having this issue, please re-open.
