### ISSUE TITLE
Full hmr-runtime support (implement full webpack HMR API)

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-react-hotloader#8]
The goal of this project was react hotloading support, which I feel we've accomplished pretty well.  However, HMR goes a lot further.  It would be great to support the full webpack HMR API, and "just work" with any module that is HMR compatible.  This can be a longer term goal of the project (time allowing) and could serve as the basis for official HMR support in Meteor.

## Strategies

**1. Wrap the Webpack HMR code as needed to work inside Meteor**

This would be my preference if it proves feasible.  Both Meteor, this project and Webpack share the MIT license.

Pros:

1. Guaranteed compatibility with Webpack HMR API
2. High degree of maintainability
3. Probably less work than implementing the API ourself.

Cons:

1. Some of the wrapping might get quite hacky, especially conversion between how we track modules to how webpack does.

**2. Implement the Webpack HMR API ourself**

Pros:

1. We understand our loader better, no need to convert data to a webpack-expected format.
2. Quicker to get a subset of the spec working initially.

Cons:

1. More work to implement and test every part of the API.
2. "Reinventing the wheel"
3. Might be harder than expected to maintain 100% API compatibilty.

**Comment by gadicc** [comment]
P.S.  For now there's just partial `hot.accept()`, which probably covers the majority of cases, especially since we'll always allow the real hot-code-push (from Meteor) to come through if there are any errors.  This might be all I have time for for the next while, but it works great!

**Comment by gadicc** [comment]
Added `hot.decline()`, `hot.dispose()` and `hot.add/removeDisposeHandler()`.  That covers the full HMR API.  Our implementation isn't nearly as good as webpack's, which is better at aborting HMRs if they'll fail in advance.  But, we don't really care about that, since, any failures will just let through the full HCP.

We don't cover the management API, especially since we do the process differently, and because modules don't need it for HMR, unless they're doing something really fancy.

Refs: http://webpack.github.io/docs/hot-module-replacement.html

cc: @clayne11

**Comment by gadicc** [comment]
Actually closing this, since I don't think we'll need anything more.  Anyone can feel free to re-open if they come across problems.

**Comment by clayne11** [comment]
This is awesome! So we should be able to hot reload the redux reducer as well?

It would be great to be able to skip the whole SCSS build / minification process as well and only load changes to those files rather than re-building the entire CSS bundle for the app on every change.

**Comment by gadicc** [comment]
Yup!  Anything that is hot code aware should work now.

We're not too far away from using this for SCSS.  We can already wrap build plugins quite easily; the plugin would just need to `addJavaScript` instead of `addStyleSheet`, and add the necessary code for each file to self-accept and dispose on updates (similar to example 2 on http://webpack.github.io/docs/hot-module-replacement.html).

As long as the build plugin doesn't use ecmascript/modules packages.  I still need to accommodate that scenario.
