### ISSUE TITLE
CSS not being loaded in when created

### ISSUE THREAD

**Issue by idmontie** [gadicc/meteor-react-hotloader#9]
When a CSS file is added to the project while Meteor is running, normally that CSS file will be loaded in.

When this package is added, the CSS file is not initially loaded in when it is created, nor will it be loaded  in when updated.

However, after refreshing the page, the CSS file is included and edits to that CSS file will be reflected in the browser as expected.

**Comment by gadicc** [comment]
Thanks for reporting.  I believe this is fixed in `v0.0.6-beta.12`, can you confirm?  This will also fix a bunch of other cases we occidentally broke.

**Comment by idmontie** [comment]
Confirmed that it works. Thanks!
